services:
- name: db
  image: "postgres:13"
  plan: starter
  envVars:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-p4ssw0rd}
    - POSTGRES_DB=openproject
  volumes:
    - name: pgdata
      path: "/var/lib/postgresql/data"

- name: cache
  image: "memcached"
  plan: starter

- name: proxy
  image: "openproject/community:${TAG:-13}"
  plan: starter
  envVars:
    - OPENPROJECT_HTTPS=${OPENPROJECT_HTTPS:-true}
    - OPENPROJECT_HOST__NAME=${OPENPROJECT_HOST__NAME:-localhost:8080}
    - OPENPROJECT_HSTS=${OPENPROJECT_HSTS:-true}
    - RAILS_CACHE_STORE=memcache
    - OPENPROJECT_CACHE__MEMCACHE__SERVER=cache:11211
    - OPENPROJECT_RAILS__RELATIVE__URL__ROOT=${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
  ports:
    - externalPort: "${PORT:-8080}"
      internalPort: 80

- name: web
  image: "openproject/community:${TAG:-13}"
  plan: starter
  envVars:
    - OPENPROJECT_HTTPS=${OPENPROJECT_HTTPS:-true}
    - OPENPROJECT_HOST__NAME=${OPENPROJECT_HOST__NAME:-localhost:8080}
    - OPENPROJECT_HSTS=${OPENPROJECT_HSTS:-true}
    - RAILS_CACHE_STORE=memcache
    - OPENPROJECT_CACHE__MEMCACHE__SERVER=cache:11211
    - OPENPROJECT_RAILS__RELATIVE__URL__ROOT=${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
  dependencies:
    - name: db
    - name: cache

- name: autoheal
  image: "willfarrell/autoheal:1.2.0"
  plan: starter
  envVars:
    - AUTOHEAL_CONTAINER_LABEL=autoheal
    - AUTOHEAL_START_PERIOD=600
    - AUTOHEAL_INTERVAL=30
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"

- name: worker
  image: "openproject/community:${TAG:-13}"
  plan: starter
  envVars:
    - OPENPROJECT_HTTPS=${OPENPROJECT_HTTPS:-true}
    - OPENPROJECT_HOST__NAME=${OPENPROJECT_HOST__NAME:-localhost:8080}
    - OPENPROJECT_HSTS=${OPENPROJECT_HSTS:-true}
    - RAILS_CACHE_STORE=memcache
    - OPENPROJECT_CACHE__MEMCACHE__SERVER=cache:11211
    - OPENPROJECT_RAILS__RELATIVE__URL__ROOT=${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
  dependencies:
    - name: db
    - name: cache

- name: cron
  image: "openproject/community:${TAG:-13}"
  plan: starter
  envVars:
    - OPENPROJECT_HTTPS=${OPENPROJECT_HTTPS:-true}
    - OPENPROJECT_HOST__NAME=${OPENPROJECT_HOST__NAME:-localhost:8080}
    - OPENPROJECT_HSTS=${OPENPROJECT_HSTS:-true}
    - RAILS_CACHE_STORE=memcache
    - OPENPROJECT_CACHE__MEMCACHE__SERVER=cache:11211
    - OPENPROJECT_RAILS__RELATIVE__URL__ROOT=${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
  dependencies:
    - name: db
    - name: cache

- name: seeder
  image: "openproject/community:${TAG:-13}"
  plan: starter
  envVars:
    - OPENPROJECT_HTTPS=${OPENPROJECT_HTTPS:-true}
    - OPENPROJECT_HOST__NAME=${OPENPROJECT_HOST__NAME:-localhost:8080}
    - OPENPROJECT_HSTS=${OPENPROJECT_HSTS:-true}
    - RAILS_CACHE_STORE=memcache
    - OPENPROJECT_CACHE__MEMCACHE__SERVER=cache:11211
    - OPENPROJECT_RAILS__RELATIVE__URL__ROOT=${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}
  dependencies:
    - name: db
    - name: cache
